### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by jeffschwartz** [jdc0589/jsformat-atom#42]
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.156.0
**System**: Mac OS X 10.10.1
**Thrown From**: [jsformat](https://github.com/jdc0589/jsformat-atom) package, v0.7.14
### Steps To Reproduce
1. ...
2. ...
### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:121

TypeError: undefined is not a function
  at Object.module.exports.format (/Users/jeffrey/.atom/packages/jsformat/lib/format.coffee:30:22)
  at /Users/jeffrey/.atom/packages/jsformat/lib/format.coffee:108:18
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:112:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:683:27)
  at /Users/jeffrey/.atom/packages/jsformat/lib/format.coffee:107:22
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:961:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:954:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:585:26)
  at Object.module.exports.autosavePaneItem (/Applications/Atom.app/Contents/Resources/app/node_modules/autosave/lib/autosave.js:56:80)
  at Object.module.exports.autosaveAllPaneItems (/Applications/Atom.app/Contents/Resources/app/node_modules/autosave/lib/autosave.js:64:28)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/autosave/lib/autosave.js:25:26

```

/cc @atom/core

**Comment by eytanbiala** [comment]
This also happens if you do not set the grammar for the file. For example:
1. Create a new file.
2. Paste in some JSON.
3. Run JsFormat
*Error is thrown.
4. Set the Grammar to JSON.
5. Run JsFormat
* Works!
