### ISSUE TITLE
 Cannot find module 'js-beautify'

### ISSUE THREAD

**Issue by rrdlpl** [jdc0589/jsformat-atom#62]
Cannot find module 'js-beautify'
Hide Stack Trace
Error: Cannot find module 'js-beautify'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\rdelaparral\AppData\Local\atom\app-1.0.3\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\rdelaparral\.atom\packages\jsformat-atom-master\lib\format.coffee:4:15)
  at Object.<anonymous> (C:\Users\rdelaparral\.atom\packages\jsformat-atom-master\lib\format.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\rdelaparral\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\rdelaparral\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:715:34)
  at C:\Users\rdelaparral\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:190:28
  at Package.module.exports.Package.measure (C:\Users\rdelaparral\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:167:15)
  at Package.module.exports.Package.load (C:\Users\rdelaparral\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\rdelaparral\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package-manager.js:373:14)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\rdelaparral\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package-manager.js:337:14)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\rdelaparral\AppData\Local\atom\app-1.0.3\resources\app.asar\src\atom.js:670:21)
  at Object.<anonymous> (C:\Users\rdelaparral\AppData\Local\atom\app-1.0.3\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\rdelaparral\AppData\Local\atom\app-1.0.3\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\rdelaparral\AppData\Local\atom\app-1.0.3\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///C:/Users/rdelaparral/AppData/Local/atom/app-1.0.3/resources/app.asar/static/index.js:96:23)
  at window.onload (file:///C:/Users/rdelaparral/AppData/Local/atom/app-1.0.3/resources/app.asar/static/index.js:36:7)

**Comment by rrdlpl** [comment]
I've just installed this package manually and whenever i open atom i'm getting that exception.

**Comment by ilanbiala** [comment]
When you say manually you mean create a folder and add code? Did you run npm install?

**Comment by rrdlpl** [comment]
I downloaded the code as a zip and extracted it in the following folder .atom/package/jsformat-atom-master

**Comment by ilanbiala** [comment]
Yes don't do that. Install it through apm next time because it will automatically run `npm install` for you. Why do you manually download packages?

**Comment by rrdlpl** [comment]
Because, I'm behind a firewall and proxy where I work and I can't download the packages with the apm command.

**Comment by ilanbiala** [comment]
@rrdlpl https://github.com/atom/apm/issues/322, does it work for you now once you run `npm install`?

**Comment by rrdlpl** [comment]
Yes, it does. By the way, I found the solution in this thread https://github.com/atom/apm/issues/322 , just in case someone else need it. Thank you for your help @ilanbiala :-)
