### ISSUE TITLE
Uncaught TypeError: atom.views.getView(...).append is not a function

### ISSUE THREAD

**Issue by santimacia** [jdc0589/jsformat-atom#64]
open a js file
change the document style to plaintext (because I prefer to not format)
save the document

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [jsformat](https://github.com/jdc0589/jsformat-atom) package, v0.9.0

### Stack Trace

Uncaught TypeError: atom.views.getView(...).append is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:809

TypeError: atom.views.getView(...).append is not a function
    at Object.module.exports.displayUnsupportedLanguageNotification (/Users/santi/.atom/packages/jsformat/lib/format.coffee:153:40)
    at Object.module.exports.format (/Users/santi/.atom/packages/jsformat/lib/format.coffee:33:8)
    at /Users/santi/.atom/packages/jsformat/lib/format.coffee:110:18
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:767:18)
    at /Users/santi/.atom/packages/jsformat/lib/format.coffee:109:22
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1012:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1004:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:584:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:547:18)
```

### Commands

```
     -0:05.5.0 grammar-selector:show (atom-text-editor.editor)
     -0:03.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:02.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:01.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.11
atom-jade, v0.3.0
esformatter, v1.13.0
jsformat, v0.9.0
linter, v1.6.0
linter-eslint, v3.0.2

# Dev
No dev packages
```

**Comment by ab3** [comment]
+1

**Comment by nicki9knuckles** [comment]
+1

**Comment by fattydevelop** [comment]
+1

**Comment by kokujin** [comment]
+1

**Comment by afkatja** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.1
**Thrown From**: [jsformat](https://github.com/jdc0589/jsformat-atom) package, v0.9.0


### Stack Trace

Uncaught TypeError: atom.views.getView(...).append is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:829

TypeError: atom.views.getView(...).append is not a function
    at Object.module.exports.displayUnsupportedLanguageNotification (/Users/katjahollaar/.atom/packages/jsformat/lib/format.coffee:153:40)
    at Object.module.exports.format (/Users/katjahollaar/.atom/packages/jsformat/lib/format.coffee:33:8)
    at /Users/katjahollaar/.atom/packages/jsformat/lib/format.coffee:110:18
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
    at /Users/katjahollaar/.atom/packages/jsformat/lib/format.coffee:109:22
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1045:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:602:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:534:18)
    at Object.module.exports.autosavePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autosave/lib/autosave.js:64:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autosave/lib/autosave.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.willDestroyPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:285:27)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:446:17)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:695:17)
```

### Commands

```
     -8:13.6.0 editor:indent (atom-text-editor.editor.is-focused)
     -8:02.1.0 core:cut (atom-text-editor.editor.is-focused)
     -7:56 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -7:56 editor:newline (atom-text-editor.editor.is-focused)
     -7:55.6.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -7:55.1.0 core:paste (atom-text-editor.editor.is-focused)
     -7:51.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:42.2.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -3:39.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:28.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:03.0 core:copy (atom-text-editor.editor.is-focused)
     -2:59.8.0 core:paste (atom-text-editor.editor.is-focused)
  9x -2:55.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:48.3.0 core:paste (atom-text-editor.editor.is-focused)
     -1:14.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:14.5.0 core:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "atom-htmltidy"
    ],
    "projectHome": "/Users/katjahollaar/Sites/Schooltas",
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
ascii-codes, v0.3.3
atom-jshint, v2.0.0
auto-update-packages, v1.0.0
autocomplete-html-entities, v0.1.0
autocomplete-sass, v0.1.0
emmet, v2.4.1
jsformat, v0.9.0
simple-drag-drop-text, v0.3.0
tabs-to-spaces, v1.0.1
terminal-status, v1.6.8
tidy-tabs, v0.3.0
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by brunowego** [comment]
+1

**Comment by ilanbiala** [comment]
Try formatting an unsupported file such as .txt with version 0.9.1

**Comment by ilanbiala** [comment]
This should be fixed in the latest version.
