### ISSUE TITLE
Uncaught ReferenceError: editor is not defined

### ISSUE THREAD

**Issue by dwerbam** [jdc0589/jsformat-atom#69]
[Enter steps to reproduce below:]

1. ...create a new file, paste some code, don't save it.
2. ...run jsformat

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [jsformat](https://github.com/jdc0589/jsformat-atom) package, v0.9.2

### Stack Trace

Uncaught ReferenceError: editor is not defined

```
At /Users/dwerbam/.atom/packages/jsformat/lib/format.coffee:153

ReferenceError: editor is not defined
    at Object.module.exports.displayUnsupportedLanguageNotification (/Users/dwerbam/.atom/packages/jsformat/lib/format.coffee:153:13)
    at Object.module.exports.format (/Users/dwerbam/.atom/packages/jsformat/lib/format.coffee:34:8)
    at atom-workspace.<anonymous> (/Users/dwerbam/.atom/packages/jsformat/lib/format.coffee:15:64)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -5:10.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 10x -5:02.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 12x -0:56.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:53.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:31.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:29.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:29.4.0 jsformat:format (atom-text-editor.editor)
     -0:07.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:06.8.0 core:copy (atom-text-editor.editor.is-focused)
     -0:05.9.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:05.2.0 core:paste (atom-text-editor.editor.is-focused)
  4x -0:04.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:02.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 jsformat:format (atom-text-editor.editor)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.6.1
jsformat, v0.9.2
language-freemarker, v0.2.0
python-tools, v0.6.7

# Dev
No dev packages
```

**Comment by mainpart** [comment]
/C:/Users/Dmitry/.atom/packages/jsformat/lib/format.coffee:161
Hide Stack Trace
ReferenceError: editor is not defined
    at Object.module.exports.displayUnsupportedLanguageNotification (file:///C:/Users/Dmitry/.atom/packages/jsformat/lib/format.coffee:153:13)
    at Object.module.exports.format (file:///C:/Users/Dmitry/.atom/packages/jsformat/lib/format.coffee:34:8)
    at atom-workspace.<anonymous> (file:///C:/Users/Dmitry/.atom/packages/jsformat/lib/format.coffee:15:64)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Dmitry\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Dmitry\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Dmitry\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Dmitry\AppData\Local\atom\app-1.5.3\resources\app.asar\src\atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)

**Comment by ilanbiala** [comment]
@dwerbam let me know if you still have this issue.
